Fix: sigma_rizzler.c: Fixed some syntax error caused by incorrect merge
There are still some errors:

~/Documents/Projects/sigma-rizzler % make
cc -O2 -Wall -Werror sigma_rizzler.c -o sigma
sigma_rizzler.c: In function ‘playerTurn’:
sigma_rizzler.c:283:13: error: too few arguments to function ‘attack’
  283 |             attack(&enemy->health);
      |             ^~~~~~
sigma_rizzler.c:217:6: note: declared here
  217 | void attack(int *hp, int turn){
      |      ^~~~~~
sigma_rizzler.c: In function ‘enemyTurn’:
sigma_rizzler.c:299:9: error: too few arguments to function ‘attack’
  299 |         attack(&user.health);
      |         ^~~~~~
sigma_rizzler.c:217:6: note: declared here
  217 | void attack(int *hp, int turn){
      |      ^~~~~~
make: *** [Makefile:16: build] Error 1